* Color-cast removal
This script will automatically color-correct the active layer, based on the average color of the active selection, or based on the whole layer if there is no selection.

Note:

The active layer will not be modified.  Instead a new color-correction layer will be created, which will be set to your chosen mode. After the script finishes you may like to try out a different layer mode.
** Installation
*** 1
Copy the "color-cast-removal.scm" file to $XDG_CONFIG_HOME/GIMP/2.10/scripts or an alternate location (chosen via Preferences -> Folders -> Scripts)
*** 2
Filters -> Script-Fu -> Refresh Scripts
** Use
*** 1 (Optional)
Select a part of the image, if you want to color correct the active layer using the inverse of the average color in the selection.

Note: If nothing is selected then the color correction will be done using the inverse of the average color of the entire active layer.
*** 2
Run the script from: Filters -> Enhance -> Color-Cast Removal...
*** 3 (Optional)
Select the mode and opacity of the color correction layer, or just leave them set to the defaults.  Experiment with changing these settings to get different effects.  A lower opacity should have less of an effect.  Soft-light mode should be less strong than the other modes.
** Tips
*** Before running the script, select part of the image which (were it not for the color cast) should be white
My best results come from first selecting a part of the image that should be white (except that it has a color cast on it). A good example of such a part of the image is snow.

I recently fixed an image of some skiers that had a strong blue cast on it. I selected the snow (which had a blue tinge to it) before running the script, and so the script used the inverse of blue (orange) for the color correction layer. If I hadn't selected everything, the script would have used the average of the entire image, which in this case would have resulted in a worse color correction because the image featured a person wearing a very bright red jacket, which made the script overcompensate towards the inverse of red (green) which didn't help.

So, judicious selection of part of the image before running the script can be very helpful.
*** Run colorize on the color correction layer after the script finishes
1 - open the colorize dialog (Colors -> Colorize) on the color correction layer

2 - set the colorize color to the inverse color that the script found and already set as your foreground color

3 - adjust the saturation and lightness in the colorize dialog to taste

This achieves the best results because you can dial in just the right amount of color correction.
*** If there's not enough color correction, try duplicating the color correction layer
*** If the effect is too strong, reduce the opacity of the color correction layer
*** For more tips and to see the technique that inspired this script in action watch this video:
[[https://www.youtube.com/watch?v=gr692iyYBUI][Colour Correction in Gimp - Removing Color Cast]] by [[https://www.youtube.com/user/Pixovert][Pixovert]]
** Testing:
This script was only tested on GIMP 2.10.8 on amd64 Gentoo Linux
** Known issues
*** There is no live preview
A live preview is impossible, since GIMP does not allow ScriptFu scripts to have a live preview.
*** There is no way for the script to open a Colorize dialog
This is another limitation of ScriptFu, as it doesn't allow GIMP dialogs to be opened by the script.
** Bug reports
Report bugs here:  https://github.com/diamond-lizard/gimp-color-cast-removal/issues
** LICENSE
Copyright (C) 2020 - Sergey Goldgaber

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
