* Color-cast removal
This script will automatically color-correct the active layer, based on the average color of the active selection, or based on the whole layer if there is no selection.

Note:

The active layer will not be modified.  Instead a new color-correction layer will be created, which will be set to your chosen mode. After the script finishes you may like to try out a different layer mode.
** Installation
*** 1
Copy the "color-cast-removal.scm" file to $XDG_CONFIG_HOME/GIMP/2.10/scripts or an alternate location (chosen via Preferences -> Folders -> Scripts)
*** 2
Filters -> Script-Fu -> Refresh Scripts
** Use
*** 1 (Optional)
Select a part of the image, if you want to color correct the active layer using the inverse of the average color in the selection.

Note: If nothing is selected then the color correction will be done using the inverse of the average color of the entire active layer.
*** 2
Run the script from: Filters -> Enhance -> Color-Cast Removal
** Testing:
This script was only tested on GIMP 2.10.8 on amd64 Gentoo Linux
** Issues and bugs
Report bugs here:  https://github.com/diamond-lizard/gimp-color-cast-removal/issues
** LICENSE
Copyright (C) 2020 - Sergey Goldgaber

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
